((nix-mode    . ((mode . apheleia)
                 (indent-tabs-mode . nil)
                 (tab-width . 2)))
 (python-mode . ((mode . apheleia)
                 (indent-tabs-mode . nil)
                 (tab-width . 4)
                 (python-indent-offset . 4)
                 (fill-column . 88)))
 (yaml-mode   . ((indent-tabs-mode . nil)
                 (tab-width . 2)
                 (yaml-indent-offset . 2)))
 (c-mode      . ((mode . apheleia)
                 (indent-tabs-mode . t)
                 (tab-width . 8)
                 (c-basic-offset . 8)
                 (c-ts-mode-indent-offset . 8)
                 (fill-column . 88)))
 (c++-mode    . ((mode . apheleia)
                 (indent-tabs-mode . t)
                 (tab-width . 8)
                 (c-basic-offset . 8)
                 (c-ts-mode-indent-offset . 8)
                 (fill-column . 88))))
