# Build on Wheezy. We use i386 because it's on amd64, it would require
# a kernel with vsyscalls enabled.
FROM i386/debian:wheezy

RUN sed -i \
        -e 's/deb.debian.org/archive.debian.org/' \
        -e 's/security.debian.org/archive.debian.org/' \
        -e '/wheezy-updates/d' \
        /etc/apt/sources.list
RUN apt-get -qqy -o Acquire::Check-Valid-Until=false update
RUN apt-get -qqy install build-essential devscripts fakeroot

COPY . /usr/src/lldpd
WORKDIR /usr/src/lldpd

RUN mk-build-deps -i debian/control -t "apt-get -o Debug::pkgProblemResolver=yes -qqy"
RUN debian/rules build && fakeroot debian/rules binary
