# Cisco ACI organizational TLV definitions
# OUI 00:01:42

[00:01:42]
vendor = Cisco

[00:01:42:203]
name = Node ID
fields = uint32

[00:01:42:205]
name = Pod ID
fields = uint16

[00:01:42:206]
name = Fabric Name
fields = string

[00:01:42:208]
name = TEP Address
fields = ipv4

[00:01:42:209]
name = Role
fields = uint8

[00:01:42:210]
name = Software Version
fields = string

[00:01:42:212]
name = Serial Number
fields = string

[00:01:42:214]
name = Model
fields = string

[00:01:42:215]
name = Node Name
fields = string

[00:01:42:220]
name = Fabric Type
fields = uint8
