.\" Copyright (c) 2006 Pierre-Yves Ritschard <pyr@openbsd.org>
.\" Copyright (c) 2008 Vincent Bernat <bernat@luffy.cx>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: July 16 2008 $
.Dt LLDPCLI 8
.Os
.Sh NAME
.Nm lldpcli ,
.Nm lldpctl
.Nd control LLDP daemon
.Sh SYNOPSIS
.Nm
.Op Fl dv
.Op Fl u Ar file
.Op Fl f Ar format
.Op Fl c Ar file
.Op Ar command ...
.Nm lldpctl
.Op Fl dv
.Op Fl u Ar file
.Op Fl f Ar format
.Op Ar interfaces ...
.Sh DESCRIPTION
The
.Nm
program controls
.Xr lldpd 8
daemon.
.Pp
When no command is specified,
.Nm
will start an interactive shell which can be used to input arbitrary
commands as if they were specified on the command line. This
interactive shell should provide completion and history support.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Enable more debugging information.
.It Fl u
Specify the Unix-domain socket used for communication with
.Xr lldpd 8 .
.It Fl v
Show
.Nm
version.
.It Fl f Ar format
Choose the output format. Currently
.Em plain ,
.Em xml ,
.Em json
and
.Em keyvalue
formats are available. The default is
.Em plain .
.It Fl c Ar file
Read the given configuration file. This option may be repeated several
times. If a directory is provided, each file contained in it will be
read  if ending by
.Li .conf .
Order is alphabetical.
.El
.Pp
When invoked as
.Nm lldpctl ,
.Nm
will display detailed information about each neighbors on the
specified interfaces or on all interfaces if none are specified. This
command is mostly kept for backward compatibility with older versions.
.Pp
The following commands are supported by
.Nm .
When there is no ambiguity, the keywords can be abbreviated. For
example,
.Cd show neighbors ports eth0 summary
and
.Cd sh neigh p eth0 sum
are the same command.
.Bd -ragged -offset XX
.Cd exit
.Bd -ragged -offset XXXXXX
Quit
.Nm .
.Ed

.Cd help Op ...
.Bd -ragged -offset XXXXXX
Display general help or help about a command. Also, you can get help
using the completion or by pressing the
.Ic ?
key. However, completion and inline help may be unavailable if
.Nm
was compiled without readline support but
.Cd help
command is always available.
.Ed

.Cd show neighbors
.Op ports Ar ethX Op ,...
.Op Cd details | summary
.Op Cd hidden
.Bd -ragged -offset XXXXXX
Display information about each neighbor known by
.Xr lldpd 8
daemon. With
.Cd summary ,
only a the name and the port description of each remote host will be
displayed. On the other hand, with
.Cd details ,
all available information will be displayed, giving a verbose
view. When using
.Cd hidden ,
also display remote ports hidden by the smart filter. When specifying
one or several ports, the information displayed is limited to the
given list of ports.
.Ed

.Cd watch
.Op ports Ar ethX Op ,...
.Op Cd details | summary
.Op Cd hidden
.Bd -ragged -offset XXXXXX
Watch for any neighbor changes and report them as soon as they
happen. When specifying ports, the changes are only reported when
happening on the given ports.
.Cd hidden , summary
and
.Cd details
have the same meaning than previously described.
.Ed

.Cd show configuration
.Bd -ragged -offset XXXXXX
Display global configuration of
.Xr lldpd 8
daemon.
.Ed

.Cd show statistics
.Op ports Ar ethX Op ,...
.Op Cd summary
.Bd -ragged -offset XXXXXX
Report LLDP-related statistics, like the number of LLDPDU transmitted,
received, discarded or unrecognized. When specifying ports, only the
statistics from the given port are reported. With
.Cd summary
the statistics of each port is summed.
.Ed

.Cd update
.Bd -ragged -offset XXXXXX
Make
.Xr lldpd 8
update its information and send new LLDP PDU on all interfaces.
.Ed

.Cd configure
.Cd lldp tx-interval Ar interval
.Bd -ragged -offset XXXXXX
Change transmit delay to the specified value in seconds. The transmit
delay is the delay between two transmissions of LLDP PDU. The default
value is 30 seconds.
.Ed

.Cd configure med fast-start
.Cd enable | tx-interval Ar interval
.Bd -ragged -offset XXXXXX
Configure LLDP-MED fast start mechanism. When a new LLDP-MED-enabled
neighbor is detected, fast start allows
.Nm lldpd
to shorten the interval between two LLDPDU.
.Cd enable
should enable LLDP-MED fast start while
.Cd tx-interval
specifies the interval between two LLDPDU in seconds. The default
interval is 1 second. Once 4 LLDPDU have been sent, the fast start
mechanism is disabled until a new neighbor is detected.
.Ed

.Cd unconfigure med fast-start
.Bd -ragged -offset XXXXXX
Disable LLDP-MED fast start mechanism.
.Ed

.Cd configure
.Op ports Ar ethX Op ,...
.Cd med location coordinate
.Cd latitude Ar latitude
.Cd longitude Ar longitude
.Cd altitude Ar altitude Ar unit
.Cd datum Ar datum
.Bd -ragged -offset XXXXXX
Advertise a coordinate based location on the given ports (or on all
ports if no port is specified). The format of
.Ar latitude
is a decimal floating point number followed either by
.Em N
or
.Em S .
The format of
.Ar longitude
is a decimal floating point number followed either by 
.Em E
or
.Em W .
.Ar altitude
is a decimal floating point number followed either by
.Em m
when expressed in meters or
.Em f
when expressed in floors. A space is expected between the floating
point number and the unit.
.Ar datum
is one of those values:
.Bl -bullet -compact -offset XXXXXXXX
.It
WGS84
.It
NAD83
.It
NAD83/MLLW
.El
.Pp
A valid use of this command is:
.D1 configure ports eth0 med location coordinate latitude 48.85667N longitude 2.2014E altitude 117.47 m datum WGS84
.Ed

.Cd configure
.Op ports Ar ethX Op ,...
.Cd med location address
.Cd country Ar country
.Cd Op Ar type value Op ...
.Bd -ragged -offset XXXXXX
Advertise a civic address on the given ports (or on all ports if no
port is specified).
.Ar country
is the two-letter code representing the country. The remaining
arguments should be paired to form the address. The first member of
each pair indicates the type of the second member which is a free-form
text. Here is the list of valid types:
.Bl -bullet -compact -offset XXXXXXXX
.It
language
.It
country-subdivision
.It
county
.It
city
.It
city-division
.It
block
.It
street
.It
direction
.It
trailing-street-suffix
.It
street-suffix
.It
number
.It
number-suffix
.It
landmark
.It
additional
.It
name
.It
zip
.It
building
.It
unit
.It
floor
.It
room
.It
place-type
.It
script
.El
.Pp
A valid use of this command is:
.D1 configure ports eth1 med location address US street Qo Commercial Road Qc city Qo Roseville Qc
.Ed

.Cd configure
.Op ports Ar ethX Op ,...
.Cd med location elin
.Ar number
.Bd -ragged -offset XXXXXX
Advertise the availability of an ELIN number. This is used for setting
up emergency call. If the provided number is too small, it will be
padded with 0. Here is an example of use:
.D1 configure ports eth2 med location elin 911
.Ed

.Cd configure
.Op ports Ar ethX Op ,...
.Cd med policy
.Cd application Ar application
.Op Cd unknown
.Op Cd vlan Ar vlan
.Op Cd priority Ar priority
.Op Cd dscp Ar dscp
.Bd -ragged -offset XXXXXX
Advertise a specific network policy for the given ports (or for all
ports if no port was provided). Only the application type is
mandatory.
.Ar application
should be one of the following values:
static const struct value_string port_med_policy_map[] = {
.Bl -bullet -compact -offset XXXXXXXX
.It
voice
.It
voice-signaling
.It
guest-voice
.It
guest-voice-signaling
.It
softphone-voice
.It
video-conferencing
.It
streaming-video
.It
video-signaling
.El
.Pp
The
.Cd unknown
flag tells that the network policy for the specified application type
is required by the device but is currently unknown. This is used by
Endpoint Devices, not by Network Connectivity Devices. If not
specified, the network policy for the given application type is
defined.
.Pp
When a VLAN is specified with
.Cd vlan
tells which 802.1q VLAN ID has to be advertised for the network
policy. A valid value is between 1 and 4094.
.Cd priority
allows one to specify IEEE 802.1d / IEEE 802.1p Layer 2 Priority, also
known as Class of Service (CoS), to be used for the specified
application type. It should be one of those values:
.Bl -bullet -compact -offset XXXXXXXX
.It
background
.It
spare
.It
best-effort
.It
excellent-effort
.It
controlled-load
.It
video
.It
voice
.It
network-control
.El
.Pp
.Ar dscp
represents the DSCP value to be advertised for the given network
policy.  DiffServ/Differentiated Services Code Point (DSCP) value as
defined in IETF RFC 2474 for the specified application type. Value: 0
(default per RFC 2475) through 63. Note: The class selector DSCP
values are backwards compatible for devices that only support the old
IP precedence Type of Service (ToS) format. (See the RFCs for what
these values mean)
.Pp
A valid use of this command is:
.D1 configure med policy application voice vlan 500 priority voice dscp 46
.Ed

.Cd configure
.Op ports Ar ethX Op ,...
.Cd med power pse | pd
.Cd source Ar source
.Cd priority Ar priority
.Cd value Ar value
.Bd -ragged -offset XXXXXX
Advertise the LLDP-MED POE-MDI TLV for the given ports or for all
interfaces if no port is provided.  One can act as a PD (power
consumer) or a PSE (power provider). No check is done on the validity
of the parameters while LLDP-MED requires some restrictions:
.Bl -bullet
.It
PD shall never request more power than physical 802.3af class.
.It
PD shall never draw more than the maximum power advertised by PSE.
.It
PSE shall not reduce power allocated to PD when this power is in use.
.It
PSE may request reduced power using conservation mode
.It
Being PSE or PD is a global paremeter, not a per-port parameter.
.Nm
does not enforce this: a port can be set as PD or PSE. LLDP-MED also
requires for a PSE to only have one power source (primary or
backup). Again,
.Nm
does not enforce this. Each port can have its own power source. The
same applies for PD and power priority. LLDP-MED MIB does not allow
this kind of representation.
.El
.Pp
Valid types are:
.Bl -tag -width "XXX." -compact -offset XX
.It Sy pse
Power Sourcing Entity (power provider)
.It Sy pd
Power Device (power consumer)
.El
.Pp
Valid sources are:
.Bl -tag -width "XXXXXXX" -compact -offset XX
.It Sy unknown
Unknown
.It Sy primary
For PSE, the power source is the primary power source.
.It Sy backup
For PSE, the power source is the backup power source or a power
conservation mode is asked (the PSE may be running on UPS for
example).
.It Sy pse
For PD, the power source is the PSE.
.It Sy local
For PD, the power source is a local source.
.It Sy both
For PD, the power source is both the PSE and a local source.
.El
.Pp
Valid priorities are:
.Bl -tag -width "XXXXXXXXX" -compact -offset XX
.It Sy unknown
Unknown priority
.It Sy critical
Critical
.It Sy high
High
.It Sy low
Low
.El
.Pp
.Ar value
should be the total power in milliwatts required by the PD device or
available by the PSE device.
.Pp
Here is an example of use:
.D1 configure med power pd source pse priority high value 5000
.Ed

.Cd configure
.Op ports Ar ethX Op ,...
.Cd dot3 power pse | pd
.Op Cd supported
.Op Cd enabled
.Op Cd paircontrol
.Cd powerpairs Ar powerpairs
.Op Cd class Ar class
.Op Cd type Ar type Cd source Ar source Cd priority Ar priority Cd requested Ar requested Cd allocated Ar allocated
.Bd -ragged -offset XXXXXX
Advertise Dot3 POE-MDI TLV for the given port or for all ports if none
was provided. One can act as a PD (power consumer) or a PSE (power
provider). This configuration is distinct of the configuration of the
transmission of the LLDP-MED POE-MDI TLV but the user should ensure
the coherency of those two configurations if they are used together.
.Pp
.Ar supported
means that MDI power is supported on the given port while
.Ar enabled
means that MDI power is enabled.
.Ar paircontrol
is used to indicate if pair selection can be controlled. Valid values
forr
.Ar powerpairs
are:
.Bl -tag -width "XXXXXX" -compact -offset XX
.It Sy signal
The signal pairs only are in use.
.It Sy spare
The spare pairs only are in use.
.El
.Pp
When specified,
.Ar class
is a number between 0 and 4.
.Pp
The remaining parameters are in conformance with 802.3at and are optional.
.Ar type
should be either 1 or 2, indicating which if the device conforms to
802.3at type 1 or 802.3at type 2. Values ofr
.Ar source
and
.Ar priority
are the same as for LLDP-MED POE-MDI TLV.
.Ar requested
and
.Ar allocated
are expressed in milliwats.
.Pp
Here are two valid uses of this command:
.D1 configure ports eth3 dot3 power pse supported enabled paircontrol powerpairs spare class 3
.D1 configure dot3 power pd supported enabled powerpairs spare class 3 type 1 source pse priority low requested 10000 allocated 15000
.Ed

.Cd pause
.Bd -ragged -offset XXXXXX
Pause
.Nm lldpd
operations.
.Nm lldpd
will not send any more frames or receive ones. This can be undone with
.Cd resume
command.
.Ed

.Cd resume
.Bd -ragged -offset XXXXXX
Resume
.Nm lldpd
operations.
.Nm lldpd
will start to send and receive frames. This command is issued
internally after processing configuration but can be used at any time
if a manual
.Cd pause
command is issued.
.Ed

.Ed
.Sh FILES
.Bl -tag -width "/var/run/lldpd.socketXX" -compact
.It /var/run/lldpd.socket
Unix-domain socket used for communication with
.Xr lldpd 8 .
.El
.Sh SEE ALSO
.Xr lldpd 8
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Vincent Bernat Aq bernat@luffy.cx .
